version: '3'
services:
  ja_dashboard:
    container_name: ja_dashboard
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    links:
      - ja_server
    depends_on:
      - ja_server
    ports:
      - "${PORT}:3000"
      - "24678:24678"
    volumes:
      - .:/app/
      - /app/node_modules
  ja_server:
    container_name: ja_server
    image: vimagick/json-server
    restart: unless-stopped
    command: -H 0.0.0.0 -p 80 -w db.json
    env_file: .env
    ports:
      - "${SERVER_PORT}:80"
    volumes:
      - ./data:/data
