version: '3'
services:
  ja_dashboard:
    container_name: ja_dashboard
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    ports:
      - "${PORT}:3000"
      - "24678:24678"
    volumes:
      - .:/app/
      - /app/node_modules
